language: python

python:
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install flake8
  - echo 'from .defaults import *' > crowdclick/settings/local.py

script:
  - coverage run manage.py test
  - coverage report
  - flake8 .

after_success:
  - codecov
